{{- if .Values.registry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registry.dockerconfig | b64enc | quote }}
{{- end }}
